### ISSUE TITLE
Add Two Categories to Playlists : Morning Routine + Night Routine

### ISSUE THREAD

**Issue by LNA** [some-lab/glow-api#4]
## DESCRIPTION
A playlist should have two category types: 
- [ ] Morning Routine
- [ ] Night Routine

- [ ] Find resources on how to implement this, and add them in the ticket so we can discuss.
- [ ] Submit a PR by next Saturday.

**Comment by astridw** [comment]
I will take this one!

**Comment by astridw** [comment]
Possible ways to approach this...

Make a model for categories in Rails
https://stackoverflow.com/questions/17758401/how-to-create-categories-in-rails#17758936

Acts as taggable on 
https://github.com/mbleigh/acts-as-taggable-on

Create a categories tree
http://www.letmefix-it.com/2017/07/21/how-to-create-nested-tree-view-ruby-on-rails/

**I choose to make a model for categories so that it can be handled within the api and associated with playlists

**Comment by astridw** [comment]
Still working on this...I am unable to generate on the rails command line. Working on fixing this issue.
